##
## Makefile for  in /blinux_home/bazin_q/rendu/PSU_2015_my_select
##
## Made by Quentin Bazin
## Login   <bazin_q@epitech.net>
##
## Started on  Tue Dec 01 15:46:23 2015 Quentin Bazin
## Last update Thu Feb 25 16:26:41 2016 Benjamin Grange
##

NAME		= asm

INC_DIRS	= include

SOURCES		= source/main.c \
		  source/asm/asm.c \
		  source/basic/error.c \
		  source/basic/memory_util.c \
		  source/basic/memory.c \
		  source/basic/putnbr.c \
		  source/basic/putstr.c \
		  source/basic/strutil.c \
		  source/compiler/compile.c \
		  source/file/file_reader_skip.c \
		  source/file/file_reader_string.c \
		  source/file/file_reader.c \
		  source/file/program_file_create.c \
		  source/lexer/lex_token.c \
		  source/lexer/lexer.c \
		  source/lexer/result.c \
		  source/lexer/syntax_error.c \
		  source/lexer/token.c \
		  source/parser/parser.c \

include ../Makefile.common
