##
## Makefile for  in /blinux_home/bazin_q/rendu/PSU_2015_my_select
##
## Made by Quentin Bazin
## Login   <bazin_q@epitech.net>
##
## Started on  Tue Dec 01 15:46:23 2015 Quentin Bazin
## Last update Thu Mar 24 14:40:32 2016 Benjamin Grange
##

NAME		= asm

INC_DIRS	= include

SOURCES		= source/main.c \
		  source/asm/asm.c \
		  source/asm/syntax_error.c \
		  source/asm/syntax_printer.c \
		  source/asm/syntax_warning.c \
		  source/basic/error.c \
		  source/basic/getnbr.c \
		  source/basic/memory_util.c \
		  source/basic/memory.c \
		  source/basic/putnbr.c \
		  source/basic/putstr.c \
		  source/basic/str_adv.c \
		  source/basic/strutil.c \
		  source/compiler/program_config.c \
		  source/file/file_reader_string.c \
		  source/file/file_reader.c \
		  source/file/program_file_create.c \
		  source/lexer/lex_comment.c \
		  source/lexer/lex_config.c \
		  source/lexer/lex_direct_label.c \
		  source/lexer/lex_identifiers.c \
		  source/lexer/lex_instruction.c \
		  source/lexer/lex_integer.c \
		  source/lexer/lex_keyword.c \
		  source/lexer/lex_label.c \
		  source/lexer/lex_operator.c \
		  source/lexer/lex_register.c \
		  source/lexer/lex_skipers.c \
		  source/lexer/lex_string.c \
		  source/lexer/lex_token.c \
		  source/lexer/lexer.c \
		  source/lexer/result.c \
		  source/lexer/result_2.c \
		  source/lexer/token_list.c \
		  source/lexer/token.c \
		  source/parser/parse_arguments.c \
		  source/parser/parse_comment.c \
		  source/parser/parse_config.c \
		  source/parser/parse_instruction.c \
		  source/parser/parse_res.c \
		  source/parser/parse_token.c \
		  source/parser/parse_whitespace.c \
		  source/parser/parser_utils.c \
		  source/parser/parser.c \
		  source/op.c

include ../Makefile.common
