##
## Makefile for  in /blinux_home/bazin_q/rendu/PSU_2015_my_select
## 
## Made by Quentin Bazin
## Login   <bazin_q@epitech.net>
## 
## Started on  Tue Dec 01 15:46:23 2015 Quentin Bazin
## Last update Sat Mar 26 23:40:20 2016 Jakob Kellendonk
##

NAME		= corewar

INC_DIRS	= include

SOURCES		= source/core/args.c \
			  source/core/application.c \
			  source/core/error.c \
			  source/core/flag_handler.c \
			  source/core/init.c \
			  source/core/main.c \
			  source/core/program.c \
			  source/core/read_helper.c \
			  source/lib/my_mem.c \
			  source/lib/my_convert.c \
			  source/lib/str.c \
			  source/run/instructions_basic.c \
			  source/run/instructions_calcul.c \
			  source/run/instructions_fork.c \
			  source/run/instructions_ld.c \
			  source/run/instructions_st.c \
			  source/run/messages.c \
			  source/run/run.c \
			  source/run/run2.c \
			  source/run/vm_copy.c \
			  source/core/op.c \

MY_LIBS		= my_printf my

include ../Makefile.libmy
include ../Makefile.common
