##
## Makefile for  in /blinux_home/bazin_q/rendu/PSU_2015_my_select
## 
## Made by Quentin Bazin
## Login   <bazin_q@epitech.net>
## 
## Started on  Tue Dec 01 15:46:23 2015 Quentin Bazin
## Last update Tue Mar  1 12:47:53 2016 Jakob Kellendonk
##

NAME		= corewar

INC_DIRS	= include

SOURCES		= source/application.c \
		  source/flag_handler.c \
		  source/flag_handler2.c \
		  source/main.c

include ../Makefile.common
